name = "PkgBump"
uuid = "ee37f239-4ffc-46a1-86ce-10bebc6017f9"
authors = ["Satoshi Terasaki <terasakisatoshi.math@gmail.com> and contributors"]
version = "0.1.0"

[deps]
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1.10"
JET = "0.9, 0.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua", "JET"]
